[package]
name = "aoc2018"
version = "0.1.0"
authors = ["Mikael Zayenz Lagerkvist <zayenz@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.1"
regex = "1.1.0"
lazy_static = "1.2.0"
num = "0.2.0"
